template header

rule
ruleId
eventType
decision
priority

package andre.replicationmigration;

import andre.replicationmigration.util.rules.RuleDecision.*;

global andre.replicationmigration.util.rules.HostDecision hostDecision;

template "host"

rule "rule_host_@{ruleId}" salience @{priority}
when
    @{eventType}(@{rule})
then
    hostDecision.setDecision(@{decision});
    hostDecision.setPriority(@{priority});
end

end template