/*
 * Register-go API
 *
 * Get apps endpoints from eureka
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type Msg struct {

	Content string `json:"content,omitempty"`
}
