template header

rule
ruleId
eventType
decision
priority

package pt.unl.fct.microservicemanagement.mastermanager;

import pt.unl.fct.microservicemanagement.mastermanager.manager.rulesystem.rules.RuleDecision;

global pt.unl.fct.microservicemanagement.mastermanager.manager.rulesystem.rules.RuleDecision containerDecision;

template "container"

rule "rule_container_@{ruleId}" salience @{priority}
when
    @{eventType}(@{rule})
then
    containerDecision.setDecision(@{decision});
    containerDecision.setPriority(@{priority});
end

end template