template header

rule
ruleId
eventType
decision
priority

package pt.unl.fct.miei.usmanagement.manager.management.rulesystem;

import pt.unl.fct.miei.usmanagement.manager.services.rulesystem.decision.Decision;

global pt.unl.fct.miei.usmanagement.manager.services.rulesystem.decision.Decision hostDecision;

template "host"

rule "host_@{ruleId}" salience @{priority}
when
    @{eventType}(@{rule})
then
    hostDecision.setDecision(@{decision});
    hostDecision.setPriority(@{priority});
end

end template