template header

rule
ruleId
eventType
decision
priority

package andre.replicationmigration;

import andre.replicationmigration.util.rules.RuleDecision.*;

global andre.replicationmigration.util.rules.ContainerDecision containerDecision;

template "container"

rule "rule_container_@{ruleId}" salience @{priority}
when
    @{eventType}(@{rule})
then
    containerDecision.setDecision(@{decision});
    containerDecision.setPriority(@{priority});
end

end template